### PR TITLE
Fixed issues after async-upgrade branch review

### PR DESCRIPTION
**Pull request by pacmancoder**
Addressed issues from #124

### CODE REVIEW

**Comment by pacmancoder** [comment]
@bcortier-devolutions A have addressed all issues from the previous PR;

Also in order to completely solve the comment https://github.com/Devolutions/devolutions-gateway/pull/124#discussion_r539598574  I am completely eliminated raw Futures (poll implementation) from jet_client.rs and replaced them with the async functions, but I still need to do some testing to validate that everything works, and after that I will make this PR non-draft

**Review by bcortier-devolutions — APPROVED** [review]
This looks all good to me! Thank you! I'll just wait for your call :smile:

**Comment by pacmancoder** [comment]
@bcortier-devolutions Branch is ready for the merge

**Comment by bcortier-devolutions** [comment]
Perfect! Good job!

**Pull request merged**
