### PR TITLE
feat(dgw): initial web application UI for standalone mode

### PR DESCRIPTION
**Pull request by kristahouse**
First WIP of Standalone Gateway UI.

### CODE REVIEW

**Comment by awakecoding** [comment]
@kristahouse are all the generated files excluded from git? I'm not familiar enough with those files types to tell, and there are a lot of them. Otherwise, just from trying it out locally, it looks good enough for a first merge.

**Comment by awakecoding** [comment]
@thenextman @bcortier-devolutions

**Review by awakecoding — APPROVED** [review]

**Review by CBenoit — COMMENTED** [review]
Small remark: should we move up all the files under `webapp/web/` to be in `webapp` instead?
I’m not sure we need to nest much more than that. What do you think?

PS: Renaming the PR to match conventional commit specification.

**Comment by CBenoit** [comment]
Merging now, we can make the other adjustments later.

**Pull request merged**
