### PR TITLE
ci: update checkout action's version

### PR DESCRIPTION
**Pull request by DannyBedard**

### CODE REVIEW

**Review by awakecoding — APPROVED** [review]

**Comment by DannyBedard** [comment]
> Switching to upload v4 breaks the workflows, because we upload to the same named artifacts multiple times.
> 
> Other fixes will be needed for this to work; is there a good reason to update or is this just housekeeping?

V4 are faster and fixes the `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20` warning. 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

For the moment, I can leave the upload to v3. When you have some time to put different name to the artifacts we can update it.

**Comment by thenextman** [comment]
@DannyBedard Happy to make the changes needed but it would be better if we can wait until after the 2024.1 release, as we really need the build to be stable right now. We can attend to it in a couple of weeks if that's ok with you.

**Review by thenextman — CHANGES_REQUESTED** [review]
We need to refactor the CI and packaging workflows before integrating this, do not merge

**Comment by thenextman** [comment]
@DannyBedard I'm making separate PRs to refactor the workflows and uplift actions versions. They will supersede this PR.

On the package.yml, I'm getting the following:

>[Upload SBOM](https://github.com/Devolutions/devolutions-gateway/actions/runs/8363180607/job/22895537636)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ./.github/workflows/cdxgen, ./.github/workflows/dtrack-upload-sbom. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I'm not sure how to correct it, we're pulling the actions repo like this:

```
      - name: Check out Devolutions/actions
        uses: actions/checkout@v4
        with:
          repository: Devolutions/actions
          ref: v1
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
          path: ./.github/workflows
```

**Comment by DannyBedard** [comment]
> @DannyBedard I'm making separate PRs to refactor the workflows and uplift actions versions. They will supersede this PR.
> 

Should we close this pull request then?

Security team will make the node20 update on our actions repo for the sbom upload, it'll fix your warning adn you'll have nothing to do.

**Comment by thenextman** [comment]
> > @DannyBedard I'm making separate PRs to refactor the workflows and uplift actions versions. They will supersede this PR.
> 
> Should we close this pull request then?
> 
> Security team will make the node20 update on our actions repo for the sbom upload, it'll fix your warning adn you'll have nothing to do.

Yes, thank you for the reminder, I will close this PR. We are fully up-to-date on all workflows apart the sec team actions. Thanks!!!

**Pull request closed without merging**
