### PR TITLE
doc: updated fontscdn link

### PR DESCRIPTION
**Pull request by dion-gionet**

### CODE REVIEW

**Review by kristahouse — CHANGES_REQUESTED** [review]
Both files give me a http 400 error.

**Comment by dion-gionet** [comment]
@kristahouse It was due to a mistake on my end which should be fixed now, however https://cdnfonts.devolutions.net/Roboto/static/Roboto.css seems to give me a different issue now, I'll look into it

**Comment by dion-gionet** [comment]
@kristahouse fixed now!

**Review by kristahouse — APPROVED** [review]
LGTM!

**Pull request merged**
